### ISSUE TITLE
Error with Kirby 2.5

### ISSUE THREAD

**Issue by MathiasGmeiner** [jenstornell/field-engineer#5]
I get this error if I try to use a engineer field in my blueprints:

`Parse error: parse error, expecting "identifier (T_STRING)"' in /Users/Sites/..../site/plugins/field-engineer/lib/presentation.php on line 91`

I'm on Kirby 2.5 with PHP 5.6.30

I tried [this example](https://github.com/jenstornell/field-engineer/blob/master/docs/blueprint.md).

**Comment by jenstornell** [comment]
I tried Kirby 2.5 now and I also get errors. Thanks for your report.

**Comment by jenstornell** [comment]
I found out that there is a problem with the toggle field with Kirby 2.5.
https://github.com/getkirby/panel/issues/1063

I'm not sure that is your problem (maybe not), but I have changed the `toggle` field to a `text` field in the "Advanced example" .

If possible, you can start upgrading to PHP7 which is faster and probably more secure.

Anyway, I keep this open.

**Comment by MathiasGmeiner** [comment]
You are write it's a PHP version incompatibility! Thanks for checking!
